title: Sarah Marshall
email: sarah@sarahmarshall.name
description:
  I'm a software engineer at Microsoft Quantum working on the compiler and
  runtime for Q#, a quantum programming language.
baseurl: ""
url: https://www.sarahmarshall.name
github_username: samarsha

timezone: America/Los_Angeles
permalink: /blog/:categories/:title:output_ext
show_excerpts: true

minima:
  date_format: "%B %-d, %Y"

disqus:
  shortname: sarah-marshall

theme: minima
plugins:
  - jekyll-feed
